cflags-y	+= -os

### HotPlugs ###
#obj-y	:= intelli_plug.o bricked_hotplug.o msm_zen_decision.o alucard_hotplug.o msm_hotplug.o mako_hotplug.o

obj-$(CONFIG_MSM_HOTPLUG) += msm_hotplug.o
#obj-$(CONFIG_INTELLI_HOTPLUG) += intelli_plug.o
obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
obj-$(CONFIG_MSM_ZEN_DECISION) += msm_zen_decision.o
obj-$(CONFIG_ALUCARD_HOTPLUG) += alucard_hotplug.o
obj-$(CONFIG_MAKO_HOTPLUG) += mako_hotplug.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o
obj-$(CONFIG_MSM_SLEEPER) += msm-sleeper.o
obj-$(CONFIG_ASMP)         += autosmp.o
