obj-$(CONFIG_MACH_MSM8974_G3_KR) += board-8974-g3-kr.o board-8974-g3-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_VZW) += board-8974-g3-us.o board-8974-g3-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_ATT) += board-8974-g3-us.o board-8974-g3-att-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_TMO_US) += board-8974-g3-us.o board-8974-g3-tmo_us-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_SPR_US) += board-8974-g3-us.o board-8974-g3-spr_us-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_GLOBAL_COM) += board-8974-g3-global.o board-8974-g3-global_com-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_CA) += board-8974-g3-ca.o board-8974-g3-ca-gpiomux.o

obj-$(CONFIG_LGE_BLUETOOTH) += board-8974-g3-rfkill.o
